export default [
['`','~',false,'ё'],
['1','!',false],
['2','"',false,'2','@'],
['3','#',false,'3','№'],
['4','$',false,'4',';'],
['5','%',false,'5','%'],
['6','^',false,'6',':'],
['7','&',false,'7','?'],
['8','*',false,'8','*'],
['9','('],
['0',')'],
['-','_'],
['=','+'],
['Backspace',null,true],

['Tab',null,true],
['q',null,false,'й'],
['w',null,false,'ц'],
['e',null,false,'у'],
['r',null,false,'к'],
['t',null,false,'е'],
['y',null,false,'н'],
['u',null,false,'г'],
['i',null,false,'ш'],
['o',null,false,'щ'],
['p',null,false,'з'],
['[','{',false,'х'],
[']','}',false,'ъ'],
['\\','|',false,'\\','/'],
['Del',null,true],

['CapsLock',null,true],
['a',null,false,'ф'],
['s',null,false,'ы'],
['d',null,false,'в'],
['f',null,false,'а'],
['g',null,false,'п'],
['h',null,false,'р'],
['j',null,false,'о'],
['k',null,false,'л'],
['l',null,false,'д'],
[';',":",false,'ж'],
[`'`,`"`,false,'э'],
['Enter',null,true],



['ShiftL',null,true],
['z',null,false,'я'],
['x',null,false,'ч'],
['c',null,false,'с'],
['v',null,false,'м'],
['b',null,false,'и'],
['n',null,false,'т'],
['m',null,false,'ь'],
[',','<',false,'б'],
['.','>',false,'ю'],
['/',":",false,'.',','],
['\u2191'],
['ShiftR',null,true],

['CtrlL',null,true],
['Win',null,true],
['AltL',null,true],
[''],
['AltR',null,true],
['CtrlR',null,true],
['\u2190'],
['\u2193'],
['\u2192'],


];